# Generated by Django 4.0.5 on 2022-07-07 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_boli_plant_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boli',
        ),
    ]
